version: 2.1
orbs:
  vault: contentful/vault@1

jobs:
  unit:
    docker:
      - image: cimg/node:18.14
    steps:
      - run: node --version
      - run: npm --version
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm ci
      - run: npm run test
  lint:
    docker:
      - image: cimg/node:18.14
    steps:
      - run: node --version
      - run: npm --version
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm ci
      - run: npm run lint
  release:
    docker:
      - image: cimg/node:18.14
    steps:
      - checkout
      - vault/get-secrets: # Loads vault secrets
          template-preset: "semantic-release"
      - run: npm ci
      - run: npm run build
      - run: npm run semantic-release
workflows:
  version: 2
  build_and_test:
    jobs:
      - unit
      - lint
      - release:
          context:
            - vault
          requires:
            - unit
            - lint
          filters:
            branches:
              only:
                - master
